[package]
name = "cch23-memark"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.12.0"
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
shuttle-rocket = "0.35.0"
shuttle-runtime = "0.35.0"
tokio = "1.26.0"
